### PR TITLE
Refactor button component 

### PR DESCRIPTION
**Pull request by julianhahn**
Refactored the button component to be more generic.

Result:

Screenshot from 2021-02-04 17-31-19

### CODE REVIEW

**Review by anbraten — CHANGES_REQUESTED** [review]
I would like to stick to our button component.

**Review by tcoro — APPROVED** [review]
I would also like to stick to our Button component, but as already mentioned couldnt find the problem why this Button Component does not center here but everywhere else.

Dont know if this after mergin https://github.com/project-leek/project-leek/pull/321 will still look uniform to the rest, will look after this after both merged

**Comment by julianhahn** [comment]
> I would like to stick to our button component. Changing the button component to be more generic and supporting such edge-case would be better IMO.

I have no ideas how to properly rework a button component to serve as a component for all our usecases.
The only option I see, is the component to be only a wrapper that serves as a background and have a slot inside. 
otherwise I think we will add too many booleans for any extra usecases.

Do you have a suggestion?

**Review by anbraten — APPROVED** [review]
lgtm :wink:

**Pull request merged**
