### PR TITLE
update mockups

### LINKED ISSUE #189: Add latest mockups to docs

### PR DESCRIPTION
**Pull request by anbraten**
closes #189

### CODE REVIEW

**Review by tcoro — CHANGES_REQUESTED** [review]
"chooseImage.png" had an Issue. I fixed the design, could you reupload it?

**Comment by anbraten** [comment]
> "chooseImage.png" had an Issue. I fixed the design, could you reupload it?

@tcoro I replaced the image.

**Review by tcoro — APPROVED** [review]

**Comment by tcoro** [comment]
why did you only add v2 and v3, but not v1?

**Review by JanEberlein — APPROVED** [review]

**Review by tcoro — COMMENTED** [review]
Why did you only add v2 and v3, but not v1?

**Comment by anbraten** [comment]
> Why did you only add v2 and v3, but not v1?

v1 was a bit difficult to export, but I tried it again and added the files

**Pull request merged**
