### PR TITLE
collect previous retro data into the report

### PR DESCRIPTION
**Pull request by tcoro**
Goal here is to collect all retro data so if someone wants to work on this topic for the report, they have all the information in one place

### CODE REVIEW

**Comment by schnickalodeon** [comment]
I am not sure if i did something wrong but i got the following Errors ehen I want to build the document:
image

**Comment by tcoro** [comment]
> I am not sure if i did something wrong but i got the following Errors ehen I want to build the document:
> image

Yes, that is "fine".
This is happening when ```/colorbox``` content is too long, the text does not linebreak and goes out of window. You can see that in the rendered pdf.

**Comment by schnickalodeon** [comment]
So you just want me to check if you put the retro stuff in the report?

**Comment by tcoro** [comment]
> So you just want me to check if you put the retro stuff in the report?

as written in the beginning of this PR

> Goal here is to collect all retro data so if someone wants to work on this topic for the report, they have all the information in one place

I didnt want to force merge this into the master (am I even allowed to do this?), so I had to go the PR Review Path

**Comment by anbraten** [comment]
@tcoro Following my part of the last retro:


Lief Gut / Besser
- Feedback im Team
- Wichtige neue Features fertig gestellt (UI-components, Welcome Screen, Home Screen, Add-Tag Screen)
- Teamtreffen

Neu Gelernt
- Vue inject & provide
- Vue Prototypes
- Raspi comitup (hotspot zum WLan einrichten)

Nicht so gut
- Zeit für Milestone / Sprint über Weihnachten & Neujahr zu lang
- 

Verbessern
- Kürzere Deadlines
- Ziele wiederholen in Meetings / klar festlegen: Was wird vom wem bis wann gemacht.
- Reviews schneller machen
- Aufgaben in kleinere Aufgaben teilen
- Zwischenstände zeigen lassen bei längeren Aufgaben

**Review by schnickalodeon — APPROVED** [review]
lgtm

**Comment by tcoro** [comment]
> @tcoro Following my part of the last retro:
> 
> Lief Gut / Besser
> 
> * Feedback im Team
> * Wichtige neue Features fertig gestellt (UI-components, Welcome Screen, Home Screen, Add-Tag Screen)
> * Teamtreffen
> 
> Neu Gelernt
> 
> * Vue inject & provide
> * Vue Prototypes
> * Raspi comitup (hotspot zum WLan einrichten)
> 
> Nicht so gut
> 
> * Zeit für Milestone / Sprint über Weihnachten & Neujahr zu lang
> 
> Verbessern
> 
> * Kürzere Deadlines
> * Ziele wiederholen in Meetings / klar festlegen: Was wird vom wem bis wann gemacht.
> * Reviews schneller machen
> * Aufgaben in kleinere Aufgaben teilen
> * Zwischenstände zeigen lassen bei längeren Aufgaben

added in f23483c0a0cd88e5fde04f4498000ced6833ceb8

**Review by JanEberlein — APPROVED** [review]
looks good :+1

**Comment by anbraten** [comment]
@tcoro I reverted your PR as it has some build errors with latex ([see here](https://github.com/project-leek/project-leek/runs/1762459043)). Please fix that first.

**Comment by tcoro** [comment]
> @tcoro I reverted your PR as it has some build errors with latex ([see here](https://github.com/project-leek/project-leek/runs/1762459043)). Please fix that first.

adressed and fixed here:
https://github.com/project-leek/project-leek/pull/307

**Pull request merged**
