### PR TITLE
improve UI based on designers feedback

### PR DESCRIPTION
**Pull request by tcoro**
* use a font with more character
* the TagID in the add window is not important to the user so make it transparent or leave it away
* more feedback than just the icon on the selected image, @ add image. Maybe a shadow and a scale transition

image

image

closes https://github.com/project-leek/project-leek/issues/310

### CODE REVIEW

**Comment by schnickalodeon** [comment]
Good work 👍 

But i think we still have this little issue. 
image
Suggestion: A little green arrow in the tag
or do we wan't to ignore that?

And maybe we should/could center anf enlarge the images (according to the 2nd Pic of Julians Notes)

**Review by schnickalodeon — CHANGES_REQUESTED** [review]
Please check my comment

**Comment by tcoro** [comment]
> Good work 👍
> 
> But i think we still have this little issue.
> image
> Suggestion: A little green arrow in the tag
> or do we wan't to ignore that?
> 
> And maybe we should/could center anf enlarge the images (according to the 2nd Pic of Julians Notes)

changed in https://github.com/project-leek/project-leek/pull/390/commits/bd4efa868a54bea49d0784ccc36a9b12be36bfa2

now looks like this:
imageimage

**Review by schnickalodeon — APPROVED** [review]
lgtm

**Review by JanEberlein — APPROVED** [review]
Looks good 👍

**Pull request merged**
