### PR TITLE
Support external images for tags

### PR DESCRIPTION
**Pull request by tcoro**
AddTagStepImage now supports external images via URL.

TODO: 
- [x] add function that tests the given URL with an regex expression if correct format
- [x] add placeholder image when no external URL Image is given
- [x] onclick function on spotifyImage and externalImage, which triggers saving clicked image as NFCTag Image
- [x] improve placeholder image

### CODE REVIEW

**Review by julianhahn — CHANGES_REQUESTED** [review]
there is still logic missing where the parent object is able to recieve the information. How would you show your results on the current branch?

**Review by schnickalodeon — APPROVED** [review]
Later we should change that we have to click on the external image, to save that to NFC-Tag

**Review by julianhahn — CHANGES_REQUESTED** [review]
could you add there a padding? I find it a bit confusing that the second text is directly under the other picture.

image

also: it seems like you check now for a valid url. But why do you not show a warnig if the input is not valid or at least make the field appear in red.

image

**Comment by tcoro** [comment]
> could you add there a padding? I find it a bit confusing that the second text is directly under the other picture.
> 
> also: it seems like you check now for a valid url. But why do you not show a warnig if the input is not valid or at least make the field appear in red.
> 
> image

image

how about this?

**Comment by tcoro** [comment]
> could you add there a padding? I find it a bit confusing that the second text is directly under the other picture.
> 
> also: it seems like you check now for a valid url. But why do you not show a warnig if the input is not valid or at least make the field appear in red.
> 
> image

It now looks like this:
image

About the error warning: Error Toasts or similiar would could be too much, since they would be thrown on every change. Coloring the Textfield would be an idea (changing the bordercolor), I could extend the props of the component. Whats your oppinion on this? Or do you have other ideas?

**Review by JanEberlein — APPROVED** [review]
looks good

**Review by julianhahn — APPROVED** [review]

**Pull request merged**
