### PR TITLE
Added .editorconfig file

### LINKED ISSUE #84: add editorconfig
- add editorconfig extension to vs-code recommended
- add .editorconfig file to repo

### PR DESCRIPTION
**Pull request by schnickalodeon**
closes #84

### CODE REVIEW

**Comment by schnickalodeon** [comment]
I don't know if we need more configuration

**Comment by anbraten** [comment]
> I don't know if we need more configuration

For the initial configuration this should be enough.

Could you also add the vs-code recommendation for the editorconfig plugin as described [here](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions)

**Review by anbraten — CHANGES_REQUESTED** [review]
Please see my prev. comment.

**Review by julianhahn — COMMENTED** [review]
is it possible to activate word-wrap as default?
especially with tailwind, could some lines get really long

**Comment by schnickalodeon** [comment]
> > I don't know if we need more configuration
> 
> For the initial configuration this should be enough.
> 
> Could you also add the vs-code recommendation for the editorconfig plugin as described [here](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions)

Done :)

**Comment by anbraten** [comment]
> is it possible to activate word-wrap as default?
> especially with tailwind, could some lines get really long

I think this can be done by some vs-code setting and is not part of the editorconfig. I would ask you to change that setting in your personal user settings as some team members probably do not want word-wrap enabled.

**Review by anbraten — APPROVED** [review]
LGTM

**Comment by schnickalodeon** [comment]
> especially with tailwind, could some lines get really long

You can do it, if you like. But I want to make that obligatory 😄

**Review by JanEberlein — APPROVED** [review]

**Pull request merged**
