### PR TITLE
import lucidchart diagrams

### PR DESCRIPTION
**Pull request by tcoro**
even though I used the export function of lucidchart, some diagrams look slightly different to others in transparency.
Is this a problem?

### CODE REVIEW

**Review by anbraten — CHANGES_REQUESTED** [review]
Im fine with the images itself as they are totally readable. 

- Please rename the folder to something more descriptive like `diagrams/activity-diagrams/...` (not 100% sure what the correct type name of these diagrams is)
- Please add a section with a link to the docs readme file (something similar to the mockups section)

**Comment by tcoro** [comment]
> Im fine with the images itself as they are totally readable.
> 
> * Please rename the folder to something more descriptive like `diagrams/activity-diagrams/...` (not 100% sure what the correct type name of these diagrams is)
> * Please add a section with a link to the docs readme file (something similar to the mockups section)

added the section to the readme in commit 74abe343c6791352a9ddee9f616167ecc6fd8373.
does this now automatically update the doc branch?

**Review by anbraten — APPROVED** [review]
Thanks.
LGTM

**Comment by schnickalodeon** [comment]
We could export the diagrams with a white background but I doubt that that is necesarry at the moment

**Pull request merged**
