### PR TITLE
322 fix bug with external image (see image)

### LINKED ISSUE #322: fix bug with external image (see image)
Error at Edit Tag: 

if you have chosen external image and edit it. It will be displayed as Spotify Image:

image

image

### PR DESCRIPTION
**Pull request by JanEberlein**
closes #322 

- fixes image source for spotify image in AddTagStepImage
- refactors AddTagStepTrack
- auto uses external image if correct url is provided
- green ring visually aids the user which image is chosen
- made images bigger for better whitespace usage

### CODE REVIEW

**Review by tcoro — APPROVED** [review]
thank you for that fix

**Review by julianhahn — CHANGES_REQUESTED** [review]
There is still a little bug: 
In the case of inserting a url for an external image
then not klicking on the image to choose it,
but directly clicking on safe,

there won't be shown any image in the overview
image

**Comment by julianhahn** [comment]
additionaly, I would really like to see a bit more feedback which image is selected.
My suggestion is a dropshadow and a scale transition on the currently selected image. Or better yet, a blue ring highliting the selected item

**Review by tcoro — APPROVED** [review]
_I solemnly swear that I am up to no good_

**Comment by tcoro** [comment]
> There is still a little bug:
> In the case of inserting a url for an external image
> then not klicking on the image to choose it,
> but directly clicking on safe,
> 
> there won't be shown any image in the overview
> image

thank you for finding that bug ❤️

**Review by julianhahn — APPROVED** [review]

**Pull request merged**
